### PR TITLE
Update README.md, Add Hungarian locale, Update description.xml 

### PR DESCRIPTION
**Pull request by ovari**
Change 3-character ellipsis `...` to a 1-character ellipsis `…`

### CODE REVIEW

**Comment by ovari** [comment]
1. Should plain quotes `"…"` be changed to smart-quotes `“…”`?
(a) Change `"""Row"" must be a valid row number (such as 1, 2, 3) and must be "` to `"“Row” must be a valid row number (such as 1, 2, 3) and must be "`?
(b) Change `"""Column"" must be a valid column name (such as A, B, C) and must be "` to `"“Column” must be a valid column name (such as A, B, C) and must be "`?

2. typo? Change `procede` to `proceed`?
(a) msgid  "Do you wish to procede?"

3. Resolves https://github.com/rafaelhlima/remove_blank_cells/issues/4#issuecomment-1072977594

4. Does Hungarian need to be initialized in any other file to enable it to work?

@rafaelhlima please advise if you require anything else to merge.

Thank you

**Comment by rafaelhlima** [comment]
Hi @ovari, first of all thanks for your contribution.

> Should plain quotes "…" be changed to smart-quotes “…”?

I would better not use smart-quotes... in Basic, to add a quote character you have to use "" (two consecutive quotes) and because it is in the beginning of the string, we have an additional quote to start the string, leaving us with """ (three consecutive quotes).

I would like to leave that as is for now, but I might change my mind in the future if this brings too many problems.

> typo? Change procede to proceed?

Indeed a typo. I'll fix it and update all .po files accordingly.

> Does Hungarian need to be initialized in any other file to enable it to work?

No, simply adding the file to the Source/po folder will suffice.

**Comment by rafaelhlima** [comment]
@ovari I noticed you used smart quotes in the Hungarian translation. I guess it looks good, specially because the language uses different quote characters. I'll leave as you suggested.

Also, thanks for the fixes in the README file. I had read it so many times and did not catch those typos. Sometimes we need someone else to read what we write 🙂

**Comment by ovari** [comment]
Thank you for using the Hungarian quotes as it is very poor to have the UI with `"` as it means `cat claws`:

> "…" [macskaköröm](https://en.wiktionary.org/wiki/macskak%C3%B6r%C3%B6m#Hungarian) (cat claws)

> I would like to leave that as is for now, but I might change my mind in the future if this brings too many problems.

Please see https://en.wikipedia.org/wiki/Quotation_mark#Summary_table for language specific smart-quotes.

Thank you once again

**Pull request merged**
